export const SUPABASE_URL = 'https://eziwjsienbxkhwpehtgp.supabase.co';
export const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6aXdqc2llbmJ4a2h3cGVodGdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjU5NDgwMTEsImV4cCI6MjA0MTUyNDAxMX0.sTP2xX0AK2lNoIVaFxMOPiTWNmiT1Xvmd0bxoKzbKTs';
